[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
fs_permissions = [{ access = "read", path = "./out"}]
verbosity = 2

# Remappings in remappings.txt

# See more config options https://github.com/gakonst/foundry/tree/master/config